# Generated by Django 2.1.7 on 2019-03-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
